### ISSUE TITLE
World Class

### ISSUE THREAD

**Issue by Tadele01** [joejnke/Deductive_systems#3]
why do you include agent_status attribute in world class?

**Comment by Tadele01** [comment]
if we use room_id to represent each room what is the relationship between room_id and room class ?
- get_room(room_id)-  do you think its a good idea to get a room based on its id what if the agent asks room that he can not possibly move based on the rule of the game?

**Comment by joejnke** [comment]
```why do you include agent_status attribute in world class?```

- because it will be used by ```get_room(room_id)``` to cross check validity of the request to get the knowledge in the room given by the ```room_id```. A request is valid if  the room given by the ```room_id``` and ```agent_status.current_room``` are neighbours. (i.e.: the agent can move from current room to the room given by ```room_id```)

- In addition, it is just to have a real world feeling and let the user interface access the information from the world assuming that the world always doesn't lie and the agent might lie when telling about it self. 
If we think it is unecessary we can let the user interface get the agent_status from the agent it self.

```if we use room_id to represent each room what is the relationship between room_id and room class ?```

I assumed that the grid will be a 2D array of rooms. So, a room in the grid can be accessed using the 2D array indexing as room_id.

```get_room(room_id)- do you think its a good idea to get a room based on its id what if the agent asks room that he can not possibly move based on the rule of the game?```

as stated above, the get_room(room_id) method uses the ```agent_status.current_room``` and returns a value if the room with ```room_id``` is  neighbour of ```agent_status.current_room``` otherwise it raises an exception or error.
